In [7]:
import os
import numpy
import matplotlib.pyplot as plt
import pandas as pd
plt.rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus']=False
plt.rcParams['font.family']

ratings = pd.read_csv('../week3/Data_processing/recommend/ratings.csv')
movies = pd.read_csv('../week3/Data_processing/recommend/movies.csv')
print(len(ratings))
print('movie record', ratings['movieId'].nunique())
ratings.head()

105339
movie record 10325

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [12]:
# user x, movie score array(unseen ;movie score= 0, movie only scores over 50)
popular = ratings.groupby('movieId').size()
popular = popular[popular >= 50].index
r_pop = ratings[ratings['movieId'].isin(popular)]
matrix = (r_pop.merge(movies, on='movieId')
        .pivot_table('rating',index='userId', columns='title')
        .fillna(0))
print('score array:', matrix.shape)
matrix

score array: (666, 455)

title,10 Things I Hate About You (1999),12 Angry Men (1957),2001: A Space Odyssey (1968),28 Days Later (2002),300 (2007),A.I. Artificial Intelligence (2001),"Abyss, The (1989)",Ace Ventura: Pet Detective (1994),Ace Ventura: When Nature Calls (1995),Addams Family Values (1993),...,While You Were Sleeping (1995),Who Framed Roger Rabbit? (1988),Wild Wild West (1999),Willy Wonka & the Chocolate Factory (1971),Witness (1985),"Wizard of Oz, The (1939)",X-Men (2000),X2: X-Men United (2003),You've Got Mail (1998),Young Frankenstein (1974)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
665,0.0,0.0,0.0,0.0,0.0,0.0,3.5,3.0,0.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
666,4.0,5.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,3.0,2.0,0.0,0.0,3.0,4.0,0.0,0.0,0.0
667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0,0.0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.5,0.0
668,2.0,4.5,3.0,3.5,2.5,4.0,3.0,0.0,0.0,3.0,...,2.0,2.0,2.0,0.0,4.0,5.0,3.0,3.5,3.0,3.0

In [13]:
#similarity
from sklearn.metrics.pairwise import cosine_similarity
item_sim = pd.DataFrame(cosine_similarity(matrix.T),
                       index=matrix.columns,
                       columns=matrix.columns)
item_sim

title,10 Things I Hate About You (1999),12 Angry Men (1957),2001: A Space Odyssey (1968),28 Days Later (2002),300 (2007),A.I. Artificial Intelligence (2001),"Abyss, The (1989)",Ace Ventura: Pet Detective (1994),Ace Ventura: When Nature Calls (1995),Addams Family Values (1993),...,While You Were Sleeping (1995),Who Framed Roger Rabbit? (1988),Wild Wild West (1999),Willy Wonka & the Chocolate Factory (1971),Witness (1985),"Wizard of Oz, The (1939)",X-Men (2000),X2: X-Men United (2003),You've Got Mail (1998),Young Frankenstein (1974)
title,,,,,,,,,,,,,,,,,,,,,
10 Things I Hate About You (1999),1.000000,0.153131,0.179531,0.301667,0.205479,0.224020,0.285079,0.268637,0.220127,0.241251,...,0.210718,0.330257,0.347694,0.295635,0.214588,0.258347,0.313965,0.294017,0.365165,0.198690
12 Angry Men (1957),0.153131,1.000000,0.287438,0.145562,0.145675,0.177754,0.258505,0.223810,0.191612,0.145471,...,0.062257,0.265592,0.152523,0.233531,0.236189,0.357459,0.269885,0.232130,0.169031,0.248459
2001: A Space Odyssey (1968),0.179531,0.287438,1.000000,0.236730,0.192413,0.332657,0.508015,0.320564,0.244103,0.268785,...,0.161596,0.408746,0.206830,0.398045,0.312366,0.434643,0.385286,0.272936,0.183338,0.434033
28 Days Later (2002),0.301667,0.145562,0.236730,1.000000,0.441689,0.379997,0.242210,0.256290,0.253968,0.182891,...,0.089590,0.262119,0.198375,0.187433,0.133403,0.212193,0.366057,0.386831,0.188642,0.089681
300 (2007),0.205479,0.145675,0.192413,0.441689,1.000000,0.357822,0.232412,0.337858,0.314312,0.209851,...,0.071137,0.241884,0.270238,0.176146,0.113358,0.103697,0.409267,0.399465,0.253513,0.127851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Wizard of Oz, The (1939)",0.258347,0.357459,0.434643,0.212193,0.103697,0.238344,0.382874,0.280009,0.207775,0.242405,...,0.214029,0.467139,0.216002,0.419739,0.429035,1.000000,0.272227,0.268094,0.219728,0.432750
X-Men (2000),0.313965,0.269885,0.385286,0.366057,0.409267,0.425604,0.475882,0.348032,0.291209,0.294671,...,0.114880,0.496754,0.369985,0.377794,0.206713,0.272227,1.000000,0.606590,0.265176,0.282022
X2: X-Men United (2003),0.294017,0.232130,0.272936,0.386831,0.399465,0.367831,0.342783,0.335113,0.317052,0.265112,...,0.129253,0.359773,0.328796,0.299085,0.175585,0.268094,0.606590,1.000000,0.298104,0.289353
You've Got Mail (1998),0.365165,0.169031,0.183338,0.188642,0.253513,0.237670,0.238172,0.249720,0.246260,0.197378,...,0.288867,0.261514,0.370249,0.230333,0.263343,0.219728,0.265176,0.298104,1.000000,0.180675
Young Frankenstein (1974),0.198690,0.248459,0.434033,0.089681,0.127851,0.229412,0.362046,0.273421,0.202571,0.246982,...,0.158980,0.407179,0.257667,0.394922,0.368935,0.432750,0.282022,0.289353,0.180675,1.000000

In [18]:
def similar_movies(title, n=5):
    return item_sim[title].drop(title).sort_values(ascending=False).head(n)

for t in ['Toy Story (1995)', 'Titanic (1997)']:
    print(f'-------if you like [{t}]------')
    print(similar_movies(t).round(2).to_string())
    print()

-------if you like [Toy Story (1995)]------
title
Star Wars: Episode VI - Return of the Jedi (1983)                                 0.63
Star Wars: Episode IV - A New Hope (1977)                                         0.63
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    0.59
Independence Day (a.k.a. ID4) (1996)                                              0.58
Back to the Future (1985)                                                         0.58

-------if you like [Titanic (1997)]------
title
Men in Black (a.k.a. MIB) (1997)    0.55
As Good as It Gets (1997)           0.53
Back to the Future (1985)           0.52
Air Force One (1997)                0.51
Saving Private Ryan (1998)          0.51

In [19]:
#user_based
user_sim = pd.DataFrame(cosine_similarity(matrix), 
                        index=matrix.index, columns=matrix.index)
user_sim

userId,1,2,3,4,5,6,7,8,9,10,...,659,660,661,662,663,664,665,666,667,668
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.123520,0.285123,0.205231,0.120235,0.114381,0.425819,0.125938,0.311977,0.048969,...,0.392476,0.223595,0.151341,0.137750,0.278104,0.227439,0.445654,0.369547,0.349253,0.476050
2,0.123520,1.000000,0.160439,0.065959,0.068973,0.042626,0.080749,0.612689,0.170085,0.000000,...,0.097563,0.000000,0.662951,0.183165,0.195055,0.092280,0.096475,0.085243,0.045774,0.197528
3,0.285123,0.160439,1.000000,0.124150,0.104856,0.021601,0.121411,0.112995,0.535979,0.142888,...,0.243035,0.340343,0.154384,0.163506,0.383547,0.132913,0.196710,0.150162,0.200775,0.330750
4,0.205231,0.065959,0.124150,1.000000,0.009619,0.013375,0.116508,0.056854,0.103249,0.000000,...,0.096339,0.058633,0.105060,0.198779,0.139684,0.032173,0.124049,0.387342,0.120787,0.345687
5,0.120235,0.068973,0.104856,0.009619,1.000000,0.136655,0.147816,0.107013,0.044682,0.037778,...,0.141888,0.019508,0.070986,0.067655,0.107627,0.081566,0.108420,0.063449,0.187822,0.196475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,0.227439,0.092280,0.132913,0.032173,0.081566,0.021224,0.320995,0.129255,0.157993,0.084240,...,0.245052,0.122347,0.120367,0.156740,0.134997,1.000000,0.197376,0.136936,0.140776,0.301618
665,0.445654,0.096475,0.196710,0.124049,0.108420,0.248475,0.318144,0.078580,0.235907,0.074334,...,0.412380,0.146450,0.051620,0.126733,0.227887,0.197376,1.000000,0.239611,0.412090,0.397292
666,0.369547,0.085243,0.150162,0.387342,0.063449,0.133881,0.296804,0.080824,0.149364,0.051877,...,0.226804,0.080368,0.069455,0.209219,0.126089,0.136936,0.239611,1.000000,0.209954,0.429643
667,0.349253,0.045774,0.200775,0.120787,0.187822,0.048836,0.257227,0.160917,0.203340,0.058992,...,0.370886,0.186589,0.076979,0.133088,0.264354,0.140776,0.412090,0.209954,1.000000,0.333278
668,0.476050,0.197528,0.330750,0.345687,0.196475,0.261244,0.440295,0.208469,0.340563,0.107906,...,0.571477,0.192463,0.258787,0.408155,0.245734,0.301618,0.397292,0.429643,0.333278,1.000000

In [26]:
def recommend_for_user(user_id, n=5, k=10):
    neighbors = (user_sim[user_id].drop(user_id).sort_values(ascending=False).head(k).index) #similar neighbor
    seen = matrix.loc[user_id][matrix.loc[user_id] >0].index #already seen
    scores = matrix.loc[neighbors].mean().drop(seen)
    return scores.sort_values(ascending=False).head(n)
target = matrix.index[0]
print(f'user {target} already seen at high score')
print(matrix.loc[target][matrix.loc[target] >=4].head(4).index.tolist())
print('recommend')
print(recommend_for_user(target).round(2).to_string())

user 1 already seen at high score
['American Beauty (1999)', 'Animal House (1978)', 'Batman Begins (2005)', 'Beautiful Mind, A (2001)']
recommend
title
Dark Knight, The (2008)                                           3.85
Memento (2000)                                                    3.65
Eternal Sunshine of the Spotless Mind (2004)                      3.45
Léon: The Professional (a.k.a. The Professional) (Léon) (1994)    3.40
V for Vendetta (2006)                                             3.30